#!/bin/sh

python HOb2sRNN.py rad_train_file opt_train_file gt_train_file rad_valid_file opt_valid_file gt_valid_file rad_test_file opt_test_file gt_test_file split_number model_outpath rad_timestamps opt_timestamps hier_pretraining